using System.ComponentModel.DataAnnotations;

public class NodalPoint
{
    public int Id { get; set; } // Auto-generated by the database

    [Required(ErrorMessage = "Location name is required.")]
    [StringLength(100, ErrorMessage = "Location name cannot be longer than 100 characters.")]
    public string LocationName { get; set; }
}
